# Generated by Django 6.0.2 on 2026-05-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombooking',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='RoomBooking',
        ),
    ]
