# Generated by Django 6.0.3 on 2026-03-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='report_photos/'),
        ),
        migrations.AddField(
            model_name='report',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='report_videos/'),
        ),
    ]
