# Generated by Django 6.0.3 on 2026-03-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_report_photo_report_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='updated_at',
        ),
    ]
