# Generated by Django 6.0.3 on 2026-03-23 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_report_photo_alter_report_video_reportmedia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='report_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
